SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE Movie_Language;
TRUNCATE TABLE Movie_Keyword;
TRUNCATE TABLE Movie_Country;
TRUNCATE TABLE Movie_Company;
TRUNCATE TABLE Movie_Genre;

TRUNCATE TABLE Keyword;
TRUNCATE TABLE Country;
TRUNCATE TABLE Company;
TRUNCATE TABLE Genre;
TRUNCATE TABLE Language;
TRUNCATE TABLE Movie;

SET FOREIGN_KEY_CHECKS = 1;